---
settings:
  name: BlueXP remediation
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: BlueXPの修正ドキュメント
    url: "/index.html"
  - title: リリースノート
    url: "/whats-new.html"
  - title: はじめに
    entries:
    - title: BlueXPの修正プログラムについて説明します
      url: "/concept-resource-templates.html"
    - title: タグ付けの詳細をご覧ください
      url: "/concept-tagging.html"
  - title: BlueXPの修復機能を使用
    entries:
    - title: テンプレートを使用して、リソース作成を標準化します
      entries:
      - title: 組織のテンプレートを作成します
        url: "/task-define-templates.html"
      - title: テンプレートのコンプライアンスについては、リソースを確認してください
        url: "/task-check-template-compliance.html"
      - title: テンプレートを実行してリソースを作成する
        url: "/task-run-templates.html"
    - title: タグを使用してリソースを整理します
      entries:
      - title: リソースのタグを管理します
        url: "/task-using-tags.html"
  - title: 概念
    entries:
    - title: テンプレートのビルディングブロック
      url: "/reference-template-building-blocks.html"
  - title: 知識とサポート
    entries:
    - title: サポートに登録します
      url: "/task-support-registration.html"
    - title: ヘルプを表示します
      url: "/task-get-help.html"
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
